# This is a basic workflow to help you get started with Actions

name: Deploy Site

on:
  push:
    branches:
      - master # only run this workflow when there's a new commit pushed to the master branch

jobs:
  deploy: # job_id
    runs-on: ubuntu-latest # environment: use ubuntu

    steps: # automated steps
      - name: Checkout Repo # 1. checkout repo
        uses: actions/checkout@v2 # Use a third party action (https://github.com/actions/checkout)

      - name: Deploy to Server # 2. deploy to remote server
        uses: AEnterprise/rsync-deploy@v1.0 # Use a third party action (https://github.com/AEnterprise/rsync-deploy)
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}} # use pre-configured secret (the private key)
          GITHUB_TOKEN: ${{secret.TOKEN}}
          ARGS: -avz --delete # must have this variable
          SERVER_PORT: "22" # SSH port
          FOLDER: ./ # folder to push (./ is the root of current repo)
          SERVER_IP: ${{secrets.SSH_HOST}} # use pre-configured ssh_host value (e.g., IP or domain.com）
          USERNAME: ${{secrets.SSH_USERNAME}} # use pre-configured ssh_username value
          SERVER_DESTINATION: /var/www/xxx/ # put your repo files on this directory of the remote server
        

